apiVersion: v1
kind: Secret
metadata:
  name: git-ssh-key
  namespace: docs
type: Opaque
stringData:
  ssh-privatekey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACDhiNOz6cpqUyeJ5Xj0vCfgculMrVARRvfTKS0MAUGHZwAAAJgwcD1zMHA9
    cwAAAAtzc2gtZWQyNTUxOQAAACDhiNOz6cpqUyeJ5Xj0vCfgculMrVARRvfTKS0MAUGHZw
    AAAECj+jXqoHFK0fEMSjwpHnwxLmav7MnJKPchUVfJwi4TceGI07PpympTJ4nlePS8J+By
    6UytUBFG99MpLQwBQYdnAAAAEW1rZG9jcy1kZXBsb3kta2V5AQIDBA==
    -----END OPENSSH PRIVATE KEY-----
  known_hosts: |
    github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
