apiVersion: v1
kind: ConfigMap
metadata:
  name: wireguard-config
  namespace: vpn
data:
  wg0.conf: |
    [Interface]
    Address = 10.100.0.1/24
    ListenPort = 51821
    PrivateKey = sEKdUANb6yiGeXYlAKqZGFQZYEc4jOu4jM5AXqaFkHA=
    PostUp = sysctl -w net.ipv4.ip_forward=1; iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
    PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

    [Peer]
    # Noah
    PublicKey = PSUtglK1hs/qtGRGJnAeNEnqzS6mI5sXhNaVJCfe01s=
    AllowedIPs = 10.100.0.2/32
