apiVersion: v1
kind: Service
metadata:
  name: wireguard
  namespace: vpn
  annotations:
    expose.neverup.at/subdomain: "vpn"
    expose.neverup.at/ports: "51821/udp"
spec:
  type: ClusterIP
  selector:
    app: wireguard
  ports:
  - name: wireguard
    port: 51821
    targetPort: 51821
    protocol: UDP
