apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-exposer-agent-config
  namespace: kube-system
data:
  config.yaml: |
    server_addr: "10.0.0.1:9090"
    cluster_domain: "neverup.at"
    sync_interval: "30s"
    watch_namespaces: []  # empty = all namespaces
